const mockData = {
  event1: {
    name: "Sydney Human Rights Conference",
    description: "A conference to discuss human rights issues and initiatives.",
    url: "http://www.google.com",
    date: "2024-08-01",
    time: "09:00",
    venue: "Sydney Convention Centre",
    city: "sydney",
    category: "human rights",
  },
  event2: {
    name: "Melbourne Human Rights Summit",
    description:
      "A summit focused on global human rights challenges and solutions.",
    url: "http://www.google.com",
    date: "2024-10-05",
    time: "10:00",
    venue: "Melbourne Town Hall",
    city: "melbourne",
    category: "human rights",
  },
  event3: {
    name: "Canberra Education Expo",
    description:
      "An expo showcasing the latest in education technology and practices.",
    url: "http://www.google.com",
    date: "2024-09-15",
    time: "11:00",
    venue: "Canberra Exhibition Centre",
    city: "canberra",
    category: "education",
  },
  event4: {
    name: "Perth Education Conference",
    description: "A conference for educators to discuss new methodologies.",
    url: "http://www.google.com",
    date: "2024-11-20",
    time: "09:30",
    venue: "Perth Convention Centre",
    city: "perth",
    category: "education",
  },
  event5: {
    name: "Adelaide Medical Symposium",
    description: "A symposium on recent advancements in medical science.",
    url: "http://www.google.com",
    date: "2024-07-10",
    time: "14:00",
    venue: "Adelaide Medical Centre",
    city: "adelaide",
    category: "medical",
  },
  event6: {
    name: "Brisbane Medical Conference",
    description: "A conference focusing on public health and medicine.",
    url: "http://www.google.com",
    date: "2024-08-22",
    time: "10:00",
    venue: "Brisbane Convention Centre",
    city: "brisbane",
    category: "medical",
  },
  event7: {
    name: "Sydney Environmental Summit",
    description:
      "A summit addressing environmental issues and sustainable practices.",
    url: "http://www.google.com",
    date: "2024-09-10",
    time: "13:00",
    venue: "Sydney Opera House",
    city: "sydney",
    category: "environment",
  },
  event8: {
    name: "Melbourne Environmental Conference",
    description: "A conference on climate change and environmental policies.",
    url: "http://www.google.com",
    date: "2024-12-05",
    time: "09:00",
    venue: "Melbourne Park",
    city: "melbourne",
    category: "environment",
  },
  event9: {
    name: "Canberra Animal Welfare Conference",
    description: "A conference dedicated to animal rights and welfare.",
    url: "http://www.google.com",
    date: "2024-10-15",
    time: "14:00",
    venue: "Canberra Civic Centre",
    city: "canberra",
    category: "animals",
  },
  event10: {
    name: "Perth Animal Rights Symposium",
    description: "A symposium on animal protection laws and advocacy.",
    url: "http://www.google.com",
    date: "2024-11-10",
    time: "10:30",
    venue: "Perth City Hall",
    city: "perth",
    category: "animals",
  },
  event11: {
    name: "Adelaide Poverty Awareness Seminar",
    description: "A seminar to raise awareness about poverty and its impacts.",
    url: "http://www.google.com",
    date: "2024-08-30",
    time: "15:00",
    venue: "Adelaide Community Centre",
    city: "adelaide",
    category: "poverty",
  },
  event12: {
    name: "Brisbane Poverty Relief Conference",
    description: "A conference discussing solutions to poverty.",
    url: "http://www.google.com",
    date: "2024-09-12",
    time: "11:00",
    venue: "Brisbane City Hall",
    city: "brisbane",
    category: "poverty",
  },
  event13: {
    name: "Sydney Global Warming Summit",
    description:
      "A summit focused on global warming and climate change solutions.",
    url: "http://www.google.com",
    date: "2024-10-01",
    time: "09:00",
    venue: "Sydney International Centre",
    city: "sydney",
    category: "global warming",
  },
  event14: {
    name: "Melbourne Climate Change Conference",
    description:
      "A conference on the effects of climate change and mitigation strategies.",
    url: "http://www.google.com",
    date: "2024-11-18",
    time: "10:00",
    venue: "Melbourne Climate Institute",
    city: "melbourne",
    category: "global warming",
  },
  event15: {
    name: "Canberra Mental Health Awareness Day",
    description: "A day dedicated to raising awareness about mental health.",
    url: "http://www.google.com",
    date: "2024-09-25",
    time: "13:00",
    venue: "Canberra Health Centre",
    city: "canberra",
    category: "mental health",
  },
  event16: {
    name: "Perth Mental Health Symposium",
    description: "A symposium on mental health challenges and solutions.",
    url: "http://www.google.com",
    date: "2024-12-01",
    time: "09:30",
    venue: "Perth Health Institute",
    city: "perth",
    category: "mental health",
  },
  event17: {
    name: "Adelaide Disaster Relief Conference",
    description:
      "A conference discussing disaster relief efforts and strategies.",
    url: "http://www.google.com",
    date: "2024-10-20",
    time: "14:00",
    venue: "Adelaide Disaster Management Centre",
    city: "adelaide",
    category: "disaster relief",
  },
  event18: {
    name: "Brisbane Disaster Management Summit",
    description: "A summit on disaster management and response.",
    url: "http://www.google.com",
    date: "2024-11-15",
    time: "10:30",
    venue: "Brisbane Crisis Centre",
    city: "brisbane",
    category: "disaster relief",
  },
  event19: {
    name: "Sydney Medical Research Conference",
    description:
      "A conference on the latest medical research and developments.",
    url: "http://www.google.com",
    date: "2024-08-15",
    time: "09:00",
    venue: "Sydney Medical Institute",
    city: "sydney",
    category: "medical",
  },
  event20: {
    name: "Melbourne Global Health Summit",
    description: "A summit addressing global health issues.",
    url: "http://www.google.com",
    date: "2024-09-20",
    time: "10:00",
    venue: "Melbourne Health Centre",
    city: "melbourne",
    category: "medical",
  },
};

export default mockData;
